-- ====================================================================
-- DỰ ÁN: FNMF - Financial News & Market Forecasting
-- CƠ SỞ DỮ LIỆU ORACLE (Schema / Connection: khoi_mobile)
-- Người thực hiện: Đặng Đức Khôi (Backend / Data Dev)
-- Ngày tạo: 19/08/2026
-- ====================================================================

-- --------------------------------------------------------------------
-- PHẦN 1: XÓA CÁC BẢNG CŨ (NẾU CÓ) ĐỂ TẠO MỚI SẠCH SẼ
-- --------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transactions CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE holdings CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE watchlists CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE wallets CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE news_ai_cache CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- --------------------------------------------------------------------
-- PHẦN 2: TẠO CÁC BẢNG CỐT LÕI CHO HỆ THỐNG
-- --------------------------------------------------------------------

-- 1. BẢNG USERS: Quản lý tài khoản đăng nhập
CREATE TABLE users (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    full_name     VARCHAR2(255) NOT NULL,
    avatar_url    VARCHAR2(500),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE users IS 'Bảng lưu trữ thông tin tài khoản người dùng';
COMMENT ON COLUMN users.password_hash IS 'Mật khẩu đã được mã hóa bằng thuật toán BCrypt';


-- 2. BẢNG WALLETS: Quản lý ví vốn ảo cho từng người dùng (Mặc định cấp $10,000 vốn ảo)
CREATE TABLE wallets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL UNIQUE,
    balance_usd     NUMBER(18, 4) DEFAULT 10000.0000 NOT NULL,
    initial_balance NUMBER(18, 4) DEFAULT 10000.0000 NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMENT ON TABLE wallets IS 'Bảng lưu ví vốn ảo cho tính năng Paper Trading';


-- 3. BẢNG HOLDINGS: Danh mục các tài sản ảo người dùng đang nắm giữ (Vàng, Dầu, BTC...)
CREATE TABLE holdings (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id     NUMBER NOT NULL,
    symbol        VARCHAR2(20) NOT NULL,               -- 'XAUUSD', 'BTCUSDT', 'USOIL'
    quantity      NUMBER(18, 8) DEFAULT 0 NOT NULL,    -- Khối lượng nắm giữ
    avg_buy_price NUMBER(18, 4) NOT NULL,              -- Giá mua trung bình
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_holding_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id) ON DELETE CASCADE,
    CONSTRAINT uq_wallet_symbol UNIQUE (wallet_id, symbol)
);

COMMENT ON TABLE holdings IS 'Bảng quản lý danh mục tài sản đang sở hữu';


-- 4. BẢNG TRANSACTIONS: Lịch sử các lệnh Mua/Bán giả lập
CREATE TABLE transactions (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id    NUMBER NOT NULL,
    symbol       VARCHAR2(20) NOT NULL,
    type         VARCHAR2(10) NOT NULL CHECK (type IN ('BUY', 'SELL')),
    price        NUMBER(18, 4) NOT NULL,              -- Giá khớp lệnh tại thời điểm giao dịch
    quantity     NUMBER(18, 8) NOT NULL,              -- Khối lượng giao dịch
    total_amount NUMBER(18, 4) NOT NULL,              -- Tổng tiền = price * quantity
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_trans_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id) ON DELETE CASCADE
);

COMMENT ON TABLE transactions IS 'Bảng lưu lịch sử tất cả lệnh Mua / Bán';


-- 5. BẢNG WATCHLISTS: Danh mục tài sản theo dõi của User (Nghiệp vụ CRUD)
CREATE TABLE watchlists (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL,
    symbol        VARCHAR2(20) NOT NULL,              -- 'XAUUSD', 'BTCUSDT', 'USOIL'
    display_order NUMBER DEFAULT 0 NOT NULL,          -- Thứ tự hiển thị ưu tiên
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_watchlist_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_symbol UNIQUE (user_id, symbol)
);

COMMENT ON TABLE watchlists IS 'Bảng lưu danh sách mã tài sản yêu thích của từng user';


-- 6. BẢNG NEWS_AI_CACHE: Lưu bài báo và kết quả tóm tắt/dự báo từ Gemini AI
CREATE TABLE news_ai_cache (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_url    VARCHAR2(1000) NOT NULL UNIQUE,
    title          VARCHAR2(500) NOT NULL,
    symbol         VARCHAR2(20),                       -- Mã tài sản liên quan ('XAUUSD', 'BTCUSDT'...)
    summary_points CLOB,                               -- Bản tóm tắt 3-5 gạch đầu dòng từ AI
    sentiment      VARCHAR2(20) CHECK (sentiment IN ('BULLISH', 'BEARISH', 'NEUTRAL')),
    confidence_pct NUMBER CHECK (confidence_pct BETWEEN 0 AND 100), -- Tỷ lệ % độ tin cậy (0 - 100)
    reason         CLOB,                               -- Lý do giải thích ngắn gọn từ AI
    published_at   TIMESTAMP,                          -- Thời gian xuất bản bài báo
    analyzed_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE news_ai_cache IS 'Bảng bộ đệm lưu kết quả phân tích AI để tránh vượt Rate Limit';


-- --------------------------------------------------------------------
-- PHẦN 3: DỮ LIỆU MẪU (MOCK DATA) ĐỂ BẠN VÀ NHÓM TEST NGAY
-- --------------------------------------------------------------------

-- 1. Thêm 1 User mẫu: khoi@fnmf.com (Mật khẩu: 123456 - đã hash bằng BCrypt)
INSERT INTO users (email, password_hash, full_name)
VALUES ('khoi@fnmf.com', '$2a$10$wK1bYnqy10L0kM0vj3.s8e.U39D5d1aB9sA5uG7K.YpG.eQWqQyqe', 'Đặng Đức Khôi');

-- 2. Khởi tạo Ví $10,000 cho user vừa tạo (User ID = 1)
INSERT INTO wallets (user_id, balance_usd, initial_balance)
VALUES (1, 10000.0000, 10000.0000);

-- 3. Thêm danh mục Watchlist mẫu cho user 1
INSERT INTO watchlists (user_id, symbol, display_order) VALUES (1, 'XAUUSD', 1);
INSERT INTO watchlists (user_id, symbol, display_order) VALUES (1, 'BTCUSDT', 2);
INSERT INTO watchlists (user_id, symbol, display_order) VALUES (1, 'USOIL', 3);

-- 4. Thêm 1 bài báo và phân tích AI mẫu vào Cache
INSERT INTO news_ai_cache (
    article_url, title, symbol, summary_points, sentiment, confidence_pct, reason
) VALUES (
    'https://fnmf.com/news/fed-rate-cut-2026',
    'Cục Dự trữ Liên bang Mỹ (FED) phát tín hiệu nới lỏng chính sách tiền tệ',
    'XAUUSD',
    '- FED để ngỏ khả năng hạ lãi suất trong kỳ họp tới.' || CHR(10) ||
    '- Lợi suất trái phiếu chính phủ Mỹ đồng loạt giảm mạnh.' || CHR(10) ||
    '- Dòng tiền của các quỹ đầu tư lớn dịch chuyển mạnh vào kim loại quý.',
    'BULLISH',
    88,
    'Lãi suất thấp làm suy yếu đồng USD và tăng sức hấp dẫn của vàng như một tài sản lưu trữ giá trị an toàn.'
);

-- Xác nhận lưu toàn bộ thay đổi
COMMIT;
