-- Migration V4: Add sandbox payment orders, wallet ledger, and payment events
-- Non-destructive, idempotent, preserves all existing user balances and data

-- Step 1: Create table PAYMENT_ORDERS
CREATE TABLE IF NOT EXISTS payment_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    wallet_id BIGINT NOT NULL,
    client_request_id VARCHAR(100) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount_usd NUMERIC(18,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    checkout_token VARCHAR(100) NOT NULL,
    provider_reference VARCHAR(100),
    failure_reason VARCHAR(255),
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_payment_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_payment_orders_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id),
    CONSTRAINT uk_payment_orders_user_client_request UNIQUE (user_id, client_request_id),
    CONSTRAINT uk_payment_orders_checkout_token UNIQUE (checkout_token)
);

CREATE INDEX IF NOT EXISTS idx_payment_orders_user_created ON payment_orders(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_orders_status ON payment_orders(status);

-- Step 2: Create table WALLET_LEDGER (Append-only audit trail)
CREATE TABLE IF NOT EXISTS wallet_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    payment_order_id BIGINT,
    entry_type VARCHAR(30) NOT NULL,
    amount_usd NUMERIC(18,2) NOT NULL,
    balance_before NUMERIC(18,2) NOT NULL,
    balance_after NUMERIC(18,2) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wallet_ledger_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id),
    CONSTRAINT fk_wallet_ledger_payment_order FOREIGN KEY (payment_order_id) REFERENCES payment_orders(id)
);

-- Exactly one ledger entry per payment order
CREATE UNIQUE INDEX IF NOT EXISTS uk_wallet_ledger_payment_order 
ON wallet_ledger(payment_order_id) 
WHERE payment_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_wallet_created ON wallet_ledger(wallet_id, created_at DESC);

-- Step 3: Create table PAYMENT_EVENTS (Webhook and processing audit trail)
CREATE TABLE IF NOT EXISTS payment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    provider_event_id VARCHAR(100) NOT NULL,
    payment_order_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    payload_hash VARCHAR(64),
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_events_order FOREIGN KEY (payment_order_id) REFERENCES payment_orders(id),
    CONSTRAINT uk_payment_events_provider_event UNIQUE (provider, provider_event_id)
);