-- Migration V9: Add content refresh quota and idempotency tracking
-- Non-destructive, compatible with both PostgreSQL and H2 (PostgreSQL mode)

CREATE TABLE IF NOT EXISTS user_daily_refresh_quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quota_date DATE NOT NULL,
    used_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_daily_refresh_quota_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_user_daily_refresh_quota UNIQUE (user_id, quota_date)
);

CREATE INDEX IF NOT EXISTS idx_user_daily_refresh_quota_lookup 
ON user_daily_refresh_quotas (user_id, quota_date);

CREATE TABLE IF NOT EXISTS content_refresh_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quota_date DATE NOT NULL,
    client_request_id VARCHAR(100) NOT NULL,
    module VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_content_refresh_event_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_content_refresh_event_client_req UNIQUE (user_id, client_request_id)
);

CREATE INDEX IF NOT EXISTS idx_content_refresh_event_user_req 
ON content_refresh_events (user_id, client_request_id);

CREATE INDEX IF NOT EXISTS idx_content_refresh_event_user_date 
ON content_refresh_events (user_id, quota_date);
